services:
  certimate:
    image: certimate/certimate:v0.3.26
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - ./data:/app/pb_data
    ports:
      - "${PANEL_APP_PORT_HTTP}:8090"
    labels:
      createdBy: "Apps"
    networks:
      - 1panel-network

networks:
  1panel-network:
    external: true
