services:
  new-api:
    image: calciumion/new-api:v0.9.0.6
    container_name: ${CONTAINER_NAME}
    restart: always
    networks:
      - 1panel-network
    labels:
      createdBy: "Apps"
    environment:
      - TZ=${TZ}
    volumes:
      - ./data:/data
    ports:
      - "${PANEL_APP_PORT_HTTP}:3000"

networks:
  1panel-network:
    external: true
